/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "rpc-hooks.h"
#define IS_PRINTABLE(c) (c > 0x1f && c < 0x7f)?c:'.'

void print_bin(unsigned char *data, int data_len){
	
	int i, k = 1;
	char arr[9] = { 0 };
	
	printf("%08p: ", data);
	for ( i = 0; i < data_len; i++){
		
		arr[k - 1] = IS_PRINTABLE(data[i]), k++;
		printf("0x%02x ", data[i]);
		
		if (k == 8){
			k = 1;
			printf("|%s|\n%08p: ", arr, data + i);
			memset(arr, 0, 9);
		}
	}
	printf("|%s|\n", arr); fflush(stdout);
	
}


int *
forward_1_svc(RPCpack *argp, struct svc_req *rqstp)
{
	static int  result;

	/*
	 * insert server code here
	 */
	 
	 printf("PROG_ID: %i\n", argp->app_id);
	 print_bin(argp->params.params_val, argp->params.params_len);

	return &result;
}
