/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "rpc-hooks.h"


void
distributedrpc_1(char *host, unsigned char *data, int data_len)
{
	CLIENT *clnt;
	int  *result_1;
	RPCpack  forward_1_arg = {50, {data_len, data} };

#ifndef	DEBUG
	clnt = clnt_create (host, distributedRPC, SPORTY, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	result_1 = forward_1(&forward_1_arg, clnt);
	if (result_1 == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	}
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;
	unsigned char *data;
	int data_len;
	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	data = argv[2];
	data_len = strlen(data);
	
	distributedrpc_1 (host, data, data_len);
	exit (0);
}
